media:
  input: public
  output: /
content:
  - name: posts
    label: Articles
    type: collection
    path: src/pages/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Publish Date
        type: date
      - name: category
        label: Category
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: draft
        label: Draft
        type: boolean
      - name: body
        label: Content
        type: rich-text
