name: 🚀 Deploy Astro to Hostinger via SFTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 🔨 Install & Build
        run: |
          npm install
          npm run build

      - name: 📂 Sync files via SFTP / rsync
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.FTP_SERVER }}
          remote-user: ${{ secrets.FTP_USERNAME }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-port: 65002
          source-path: dist/
          destination-path: /home/u194847263/domains/newbeltane.co.uk/public_html/
